sources:
  # === LLM & AI Blogs ===
  - name: OpenAI News
    url: https://openai.com/news/rss.xml
    category: LLM
  - name: Google AI Blog
    url: https://blog.google/technology/ai/rss/
    category: LLM
  - name: Microsoft AI Blog
    url: https://blogs.microsoft.com/ai/feed/
    category: LLM
  # Note: Anthropic doesn't have an official RSS feed - removed for now

  # === Cloud Provider Updates ===
  - name: AWS News
    url: https://aws.amazon.com/about-aws/whats-new/recent/feed/
    category: Cloud
  - name: Azure Updates
    url: https://azurecomcdn.azureedge.net/en-us/updates/feed/
    category: Cloud
  - name: Google Cloud Blog
    url: https://cloud.google.com/feeds/blog.xml
    category: Cloud

  # === Security News Websites ===
  - name: TechRadar Pro Security
    url: https://www.techradar.com/feeds/tag/security
    category: Security
  - name: Dark Reading
    url: https://www.darkreading.com/rss_simple.asp
    category: Security
  - name: Krebs on Security
    url: https://krebsonsecurity.com/feed/
    category: Security
  - name: The Hacker News
    url: https://feeds.feedburner.com/TheHackersNews
    category: Security
  - name: BleepingComputer
    url: https://www.bleepingcomputer.com/feed/
    category: Security
  - name: SC Magazine
    url: https://www.scmagazine.com/home/feed/
    category: Security
  - name: SecurityWeek
    url: https://feeds.feedburner.com/securityweek
    category: Security
  - name: Help Net Security
    url: https://www.helpnetsecurity.com/feed/
    category: Security
  - name: Bruce Schneier Blog
    url: https://www.schneier.com/blog/atom.xml
    category: Security
  - name: TheRegister
    url: https://www.theregister.com/headlines.atom
    category: Tech

  # === Vulnerability & CVE Feeds ===
  - name: CVE Feed (High/Critical)
    url: https://cvefeed.io/rssfeed/
    category: Vulnerability
  - name: CVE Details Recent
    url: https://www.cvedetails.com/vulnerability-feeds-form.php?type=rss&orderby=3&cvssscoremin=7
    category: Vulnerability
  - name: Rapid7 Vulnerability Research
    url: https://blog.rapid7.com/tag/vulnerability-research/rss/
    category: Vulnerability
  - name: Tenable Research
    url: https://www.tenable.com/blog/rss.xml
    category: Vulnerability
  - name: VulnDB
    url: https://vuldb.com/rss.xml
    category: Vulnerability
  - name: ExploitDB
    url: https://www.exploit-db.com/rss.xml
    category: Vulnerability
  - name: Qualys VMDR Blog
    url: https://blog.qualys.com/feed
    category: Vulnerability

  # === Threat Intelligence & Research ===
  - name: Recorded Future Threat Intelligence
    url: https://www.recordedfuture.com/feed/
    category: ThreatIntel
  - name: CrowdStrike Blog
    url: https://www.crowdstrike.com/blog/feed/
    category: ThreatIntel
  - name: Cisco Talos Intelligence
    url: https://blog.talosintelligence.com/feeds/posts/default
    category: ThreatIntel
  - name: Malwarebytes Labs
    url: https://blog.malwarebytes.com/feed/
    category: ThreatIntel
  - name: Palo Alto Networks Unit 42
    url: https://unit42.paloaltonetworks.com/feed/
    category: ThreatIntel
  - name: SANS Internet Storm Center
    url: https://isc.sans.edu/rssfeed.xml
    category: ThreatIntel
  - name: Microsoft Security Blog
    url: https://www.microsoft.com/en-us/security/blog/feed/
    category: Security
  - name: US-CERT National Cyber Awareness System
    url: https://us-cert.cisa.gov/ncas/alerts.xml
    category: ThreatIntel
  - name: Fortinet Blog
    url: https://blog.fortinet.com/rss.xml
    category: ThreatIntel

  # === Asia-Pacific Regulatory & Security Feeds ===
  - name: Singapore MAS
    url: https://www.mas.gov.sg/rss/news
    category: Regulation
  - name: Singapore CSA
    url: https://www.csa.gov.sg/rss/news
    category: Security
  - name: Japan NISC
    url: https://www.nisc.go.jp/rss/eng-news.xml
    category: Security
  - name: India CERT-In
    url: https://www.cert-in.org.in/rss
    category: Security
  - name: Hong Kong PCPD
    url: https://www.pcpd.org.hk/rss/press.xml
    category: Regulation
  - name: Philippines NPC
    url: https://www.privacy.gov.ph/rss/feed.xml
    category: Regulation
  - name: Korea KISA
    url: https://www.kisa.or.kr/rss/eng.xml
    category: Security
  - name: Malaysia MyCERT
    url: https://www.mycert.org.my/rss
    category: Security

filters:
  keywords:
    # AI & LLM
    - LLM
    - GPT
    - "large language model"
    - "generative AI"
    - "multimodal AI"
    - "AI model release"
    - "AI safety"
    - "AI governance"
    - "AI regulation"
    - "AI policy"
    - "autonomous agent"
    - "AI red teaming"
    - "AI ethics"
    - "AI security"
    - "AI misuse"
    - "prompt injection"
    - "model inversion"
    - "AI hallucination"
    - "machine learning security"
    - "adversarial attack"
    - "model poisoning"
    - "data poisoning"

    # Vulnerability & CVE Specific
    - "CVE-"
    - "critical vulnerability"
    - "high severity"
    - "remote code execution"
    - "privilege escalation"
    - "buffer overflow"
    - "SQL injection"
    - "cross-site scripting"
    - "authentication bypass"
    - "information disclosure"
    - "denial of service"
    - "memory corruption"
    - "use after free"
    - "path traversal"
    - "CVSS"
    - "exploit available"
    - "proof of concept"
    - "vulnerability disclosure"
    - "security advisory"
    - "patch available"
    # Cybersecurity Threats
    - "critical vulnerability"
    - CVE-
    - "supply chain attack"
    - ransomware
    - "malware campaign"
    - "APT"
    - "nation-state actor"
    - "cyber espionage"
    - "data breach"
    - "phishing"
    - "credential theft"
    - "initial access broker"
    - "threat actor"
    - "incident response"
    - "forensic analysis"
    - "reverse engineering"
    - "exploit kit"
    - "botnet"
    - "command and control"

    # Cloud Security
    - "cloud security"
    - "cloud misconfiguration"
    - "cloud breach"
    - "S3 bucket"
    - "IAM misconfiguration"
    - "cloud pentest"
    - "container escape"
    - "kubernetes security"
    - "multi-cloud"
    - "zero trust"
    - "cloud workload protection"
    - "cloud compliance"

    # Cybercrime & Investigations
    - "cybercrime"
    - "digital forensics"
    - "threat intel"
    - "dark web"
    - "cyber fraud"
    - "business email compromise"
    - "crypto theft"
    - "SIM swapping"
    - "money mule"
    - "underground forum"
    - "cyber extortion"

    # Regulations (Global)
    - DORA
    - NIS2
    - "SEC cyber rule"
    - GDPR
    - "EU AI Act"
    - "data sovereignty"
    - "privacy law"
    - FISMA
    - "PCI DSS"
    - "ISO 27001"
    - "critical infrastructure"
    - "national security directive"
    - "OFAC sanctions"

    # Asia-Pacific Specific Regulations
    - "Cybersecurity Law of China"
    - "China Data Security Law"
    - "China Personal Information Protection Law"
    - PIPL
    - "MLPS 2.0"
    - "APAC privacy law"
    - "Singapore PDPA"
    - "Singapore Cybersecurity Act"
    - "MAS TRM"
    - "Australia Privacy Act"
    - "Australian Cyber Security Strategy"
    - "Australian Critical Infrastructure Act"
    - "New Zealand Privacy Act"
    - "Japan APPI"
    - "Japan Cybersecurity Basic Act"
    - "Korea PIPA"
    - "Korea Network Act"
    - "India Digital Personal Data Protection Act"
    - "India CERT-In directives"
    - "Hong Kong PDPO"
    - "Philippines Data Privacy Act"
    - "Vietnam Cybersecurity Law"
    - "Vietnam Data Localization Law"
    - "Thailand PDPA"
    - "Malaysia PDPA"
    - "Indonesia PDP Law"
    - "Taiwan Personal Data Protection Act"
    - "Myanmar E-Commerce Law"
    - "Cambodia PDPA"

# optional settings
log_level: "DEBUG"
fuzz_threshold: 0.8
max_per_domain: 2
max_results: 10